import { writeFileSync } from 'fs';
import { resolve } from 'path';
import { MASTER } from '../src/data/master';

const API_KEY = process.env.GOOGLE_PLACES_API_KEY;

if (!API_KEY) {
  console.error("Please set GOOGLE_PLACES_API_KEY environment variable.");
  process.exit(1);
}

const ENDPOINT = 'https://places.googleapis.com/v1/places:searchText';
const FIELD_MASK = 'places.id,places.displayName,places.reviews';

const genericCorpus = `
instagrammable brunch pasta aircon wifi portion queue seating aesthetic
vibe noisy crowded overrated cheap fast friendly staff
waitress table location parking
`.split(/\s+/).filter(Boolean);

async function run() {
  console.log('Building Gem Lexicon from archive...');
  const uniqueCafes = [...new Set(MASTER.map(m => m.Cafe_Name).filter(Boolean))];
  
  let allReviewsText = "";

  for (const cafe of uniqueCafes) {
    try {
      console.log(`Fetching reviews for ${cafe}...`);
      const payload = {
        textQuery: `${cafe} specialty coffee`,
        maxResultCount: 1,
        languageCode: 'en'
      };
      
      const res = await fetch(ENDPOINT, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'X-Goog-Api-Key': API_KEY,
          'X-Goog-FieldMask': FIELD_MASK,
          'Referer': 'https://hari-gatekeeper-app.netlify.app'
        },
        body: JSON.stringify(payload)
      });
      
      if (!res.ok) {
        console.error(`Failed to fetch ${cafe}: ${res.statusText}`);
        continue;
      }
      
      const data = await res.json();
      const place = data.places?.[0];
      if (place?.reviews) {
        for (const review of place.reviews) {
          if (review.text?.text) {
            allReviewsText += " " + review.text.text.toLowerCase();
          }
        }
      }
    } catch (err) {
      console.error(`Error for ${cafe}:`, err);
    }
  }

  // Stop words to filter out
  const stopWords = new Set(["the","and","for","was","with","they","that","their","you","this","but","from","are","well","one","really","also","just","very","more","were","which","not","have","out","time","what","here","there","can","about","would","some","too","both","when","quite","will","even","our","only","all","than","around","get","bit","come","who","its","how","into","could","new","has","had","been","like","much","other","then","because","any","these","those"]);
  
  // Tokenize and count
  const words = allReviewsText.match(/\b[a-z]{3,}\b/g) || [];
  const counts = new Map<string, number>();
  for (const w of words) {
    if (genericCorpus.includes(w) || stopWords.has(w)) continue;
    counts.set(w, (counts.get(w) || 0) + 1);
  }

  // Sort and pick top 150
  const sorted = [...counts.entries()].sort((a, b) => b[1] - a[1]);
  const gemLexicon = sorted.slice(0, 150).map(e => e[0]);

  // Fallback to expected if API didn't return much
  if (gemLexicon.length < 10) {
    console.log("Not enough data fetched. Using default expected lexicon.");
    gemLexicon.push(
      ...["brew", "bar", "roast", "date", "single", "origin", "tasting", "notes",
      "pourover", "barista", "recommended", "beans", "sale", "rotating", "seasonal",
      "acidity", "fruity", "funky", "filter", "aeropress", "gesha", "ethiopia",
      "anaerobic", "competition", "brewers", "cup", "kalita", "slow", "omakase", "flight"]
    );
  }

  const outPath = resolve(process.cwd(), 'src/data/gem-lexicon.ts');
  const outContent = `// Auto-generated by scripts/build-lexicon.ts
export const GEM_LEXICON = ${JSON.stringify([...new Set(gemLexicon)])};
export const GENERIC_LEXICON = ${JSON.stringify(genericCorpus)};
`;

  writeFileSync(outPath, outContent);
  console.log(`Successfully wrote ${outPath}`);
}

run().catch(console.error);
